name: Github Pages Deploy

on: 
  push:
    branches: master
    
jobs:
  github-pages-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
    
    - name: Setup .Net 7
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'
        include-prerelease: false
      
    - name: Publish .Net Core Project
      run: dotnet publish TgEng.csproj -c Release --output release --nologo
      
    - name: Uploading files to gh-pages branch
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: release/wwwroot
